#!/usr/bin/perl

use strict;
use warnings;
use lib 'lib';
use Curses::Readline qw(curses_readline);
use Curses;
use Encode;

initscr;
noecho;
cbreak;
keypad(1);

my $result = curses_readline;

endwin;

if ( not defined $result ) {
	warn "Could not read line!\n";
	exit 1;
}

print encode('utf8',$result) . "\n";

exit 0;
